[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "mkdir -p episodes uploads templates static logs",
  "chmod 755 episodes uploads templates static logs"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 2 web_app_production:app"
